### ISSUE TITLE
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by lukasoppermann** [kroleg/shipit-deploy-simple-fetch#1]
Hey, I am getting the following error when using the package. It does work without the package (but is slow).

> 'deploy:update' errored after 9.53 s
> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
>     at validateString (internal/validators.js:122:11)
>     at Object.resolve (path.js:980:7)
>     at /Users/lukasoppermann/Repos/veare/node_modules/shipit-deploy/lib/tasks/deploy/update.js:104:45
>     at Generator.next (<anonymous>)
>     at asyncGeneratorStep (/Users/lukasoppermann/Repos/veare/node_modules/shipit-deploy/lib/tasks/deploy/update.js:26:103)
>     at _next (/Users/lukasoppermann/Repos/veare/node_modules/shipit-deploy/lib/tasks/deploy/update.js:28:194)
>     at /Users/lukasoppermann/Repos/veare/node_modules/shipit-deploy/lib/tasks/deploy/update.js:28:364
>     at new Promise (<anonymous>)
>     at /Users/lukasoppermann/Repos/veare/node_modules/shipit-deploy/lib/tasks/deploy/update.js:28:97
>     at _remoteCopy (/Users/lukasoppermann/Repos/veare/node_modules/shipit-deploy/lib/tasks/deploy/update.js:116:26)
>     at remoteCopy (/Users/lukasoppermann/Repos/veare/node_modules/shipit-deploy/lib/tasks/deploy/update.js:90:26)
>     at Shipit.<anonymous> (/Users/lukasoppermann/Repos/veare/node_modules/shipit-deploy/lib/tasks/deploy/update.js:214:11)
>     at Generator.next (<anonymous>)
>     at asyncGeneratorStep (/Users/lukasoppermann/Repos/veare/node_modules/shipit-deploy/lib/tasks/deploy/update.js:26:103)
>     at _next (/Users/lukasoppermann/Repos/veare/node_modules/shipit-deploy/lib/tasks/deploy/update.js:28:194)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)

My setup is:

```js
module.exports = shipit => {
  // Load shipit-deploy tasks
  require('shipit-deploy')(shipit)

  // const fetch = require('shipit-deploy-simple-fetch')(shipit)

  shipit.initConfig({
    default: {
      branch: 'master',
      workspace: '/tmp/deploy/workspace',
      deployTo: '/home/test',
      repositoryUrl: 'https://github.com/lukasoppermann/veare.git',
      shallowClone: true,
      keepReleases: 5,
      deleteOnRollback: false
    },
    production: {
      servers: //'...',
    }
  })
}
```

Am I doing something wrong? Thank you.

**Comment by kroleg** [comment]
I don't think that your problem is related to `shipit-deploy-simple-fetch` because `require('shipit-deploy-simple-fetch')` is commented out

**Comment by kroleg** [comment]
If this error is related to `shipit-deploy-simple-fetch` it might be because this package is too old and is not compatible with latest `shipit`. And if it's the case i suggest you to not use my package at all.
Latest shipit-deploy already has `shallowClone` https://github.com/shipitjs/shipit/tree/master/packages/shipit-deploy#workspace

**Comment by lukasoppermann** [comment]
I actually did not have it commented out when trying. 😂

Maybe it is to old. So it is not actively maintained anymore?

**Comment by kroleg** [comment]
This one? Nope
